spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: 60s
        max-idle: 8
        min-idle: 1
      shutdown-timeout: 10s
    port: 6379
    database: 0
    timeout: 10s
    host: localhost
